version: '3.1'

networks:
  testnetwork:

services:

  dotnet_sdk:
    image: tursoft/pardus-dotnetcore:2.2.104-sdk
    command:
      - 'dotnet --version'
      - 'sleep infinity'
    networks:
      - testnetwork