version: '3.1'

networks:
  testnetwork:

services:

  dotnet_runtime:
    image: tursoft/pardus-dotnetcore:2.2.2
    entrypoint: dotnet --version && sleep 99999999
    restart: always
    networks:
      - testnetwork    