version: '3.1'

networks:
  testnetwork:

services:

  dotnet_runtime:
    image: tursoft/pardus-dotnetcore:2.2.2
    command:
      - 'dotnet --version'
      - 'sleep infinity'
    restart: always
    networks:
      - testnetwork    