version: '3.1'

networks:
  testnetwork:

services:

  dotnet_sdk_ornek:
    image: tursoft/pardus-dotnetcore:2.2.104-sdk-ornek
    entrypoint: dotnet test --logger:trx && sleep 99999999   
    networks:
      - testnetwork    